# Hermetic Docker Compose for Lethe vNext Research
# Local-first architecture with SQLite-only datastore and network isolation
# Complies with: TODO.md requirements for hermetic reproducibility

version: '3.9'

networks:
  # Internal network - completely isolated from external access
  lethe-hermetic:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  # Localhost-only network for Ollama communication
  lethe-localhost:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  # SQLite database storage
  lethe-sqlite-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/sqlite
  # Artifacts and results storage
  lethe-artifacts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../artifacts
  # Vector index storage (HNSW WASM)
  lethe-index-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/indices

services:
  # Core Lethe Research Service
  lethe-research:
    build:
      context: ..
      dockerfile: infra/Dockerfile.hermetic
      args:
        - BUILDKIT_INLINE_CACHE=1
        - BUILD_DATE=${BUILD_DATE:-}
        - VCS_REF=${VCS_REF:-}
        - VERSION=${VERSION:-1.0.0}
    image: lethe-research:hermetic
    container_name: lethe-research
    restart: no  # No auto-restart in hermetic mode
    networks:
      - lethe-hermetic
      - lethe-localhost
    ports:
      # Only localhost binding for readiness checks
      - "127.0.0.1:8080:8080"
    volumes:
      - lethe-sqlite-data:/app/data/sqlite:rw
      - lethe-artifacts:/app/artifacts:rw
      - lethe-index-data:/app/data/indices:rw
      - ../datasets:/app/datasets:ro
      - ../verification:/app/verification:ro
      - ../experiments:/app/experiments:ro
      - ../scripts:/app/scripts:ro
      - ./config/hermetic.json:/app/config/config.json:ro
    environment:
      - ENVIRONMENT=hermetic
      - NETWORK_MODE=isolated
      - DATASTORE_TYPE=sqlite
      - SQLITE_PATH=/app/data/sqlite/lethe.db
      - VECTOR_INDEX_PATH=/app/data/indices
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - OLLAMA_HOST=http://host.docker.internal:11434
      - DISABLE_OUTBOUND_NETWORK=1
      - HERMETIC_MODE=1
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/sqlite/lethe.db').execute('SELECT 1').fetchone()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=1G
      - /var/tmp:noexec,nosuid,size=256M
      - /app/logs:noexec,nosuid,size=512M
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'

  # Smoke Test Service (runs once for validation)
  lethe-smoke-test:
    build:
      context: ..
      dockerfile: infra/Dockerfile.hermetic
      target: smoke-test
    image: lethe-smoke-test:hermetic
    container_name: lethe-smoke-test
    networks:
      - lethe-hermetic
    volumes:
      - lethe-sqlite-data:/app/data/sqlite:ro
      - lethe-artifacts:/app/artifacts:rw
      - ../scripts:/app/scripts:ro
    environment:
      - ENVIRONMENT=hermetic
      - SMOKE_TEST_MODE=1
      - SQLITE_PATH=/app/data/sqlite/lethe.db
    depends_on:
      lethe-research:
        condition: service_healthy
    profiles:
      - smoke-test
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=256M
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

  # Environment Manifest Generator (runs once to record environment)
  lethe-env-recorder:
    build:
      context: ..
      dockerfile: infra/Dockerfile.hermetic
      target: env-recorder
    image: lethe-env-recorder:hermetic
    container_name: lethe-env-recorder
    networks:
      - lethe-hermetic
    volumes:
      - lethe-artifacts:/app/artifacts:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ENVIRONMENT=hermetic
      - RECORD_ENV_MODE=1
    command: ["python", "scripts/record_env.py", "--out", "/app/artifacts/env_manifest.json"]
    profiles:
      - env-record
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=256M
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

# Network isolation enforcement
x-network-policies: &network-policies
  sysctls:
    - net.ipv4.ip_forward=0
    - net.ipv6.conf.all.forwarding=0
    - net.ipv4.conf.all.send_redirects=0
    - net.ipv4.conf.default.send_redirects=0