[workspaces]
packages = [
  "api-server",
  "cli",
  "core",
  "llm-analyzer",
  "tokenizer",
  "types"
]

[install]
frozenLockfile = false

[test]
root = "tests"
coverage = true
importmap = "./import-map.json"

[run]
importmap = "./import-map.json"
