use async_trait::async_trait;
use lethe_shared::{Result, LetheError, EmbeddingVector};
use crate::embeddings::EmbeddingService;
use serde::{Deserialize, Serialize};
use std::sync::Arc;

/// HyDE (Hypothetical Document Embeddings) configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HydeConfig {
    /// Number of hypothetical documents to generate
    pub num_documents: usize,
    /// Temperature for document generation
    pub temperature: f32,
    /// Maximum tokens for generated documents
    pub max_tokens: usize,
    /// Whether to combine hypothetical with original query
    pub combine_with_query: bool,
}

impl Default for HydeConfig {
    fn default() -> Self {
        Self {
            num_documents: 3,
            temperature: 0.7,
            max_tokens: 256,
            combine_with_query: true,
        }
    }
}

/// Hypothetical document generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HypotheticalDocument {
    pub id: String,
    pub text: String,
    pub embedding: Option<EmbeddingVector>,
    pub confidence: f32,
}

/// HyDE query expansion result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HydeExpansion {
    pub original_query: String,
    pub hypothetical_documents: Vec<HypotheticalDocument>,
    pub combined_embedding: Option<EmbeddingVector>,
    pub expansion_quality: f32,
}

/// Trait for LLM services that can generate hypothetical documents
#[async_trait]
pub trait LlmService: Send + Sync {
    async fn generate_text(&self, prompt: &str, config: &HydeConfig) -> Result<Vec<String>>;
}

/// HyDE service for query expansion using hypothetical documents
pub struct HydeService {
    llm_service: Arc<dyn LlmService>,
    embedding_service: Arc<dyn EmbeddingService>,
    config: HydeConfig,
}

impl HydeService {
    pub fn new(
        llm_service: Arc<dyn LlmService>,
        embedding_service: Arc<dyn EmbeddingService>,
        config: HydeConfig,
    ) -> Self {
        Self {
            llm_service,
            embedding_service,
            config,
        }
    }

    /// Expand a query using HyDE methodology
    pub async fn expand_query(&self, query: &str) -> Result<HydeExpansion> {
        // Generate hypothetical documents
        let hypothetical_texts = self.generate_hypothetical_documents(query).await?;
        
        // Create hypothetical document objects
        let mut hypothetical_documents = Vec::new();
        for (i, text) in hypothetical_texts.into_iter().enumerate() {
            let id = format!("hyde_{}", i);
            let embedding = self.embedding_service.embed(&[text.clone()]).await?;
            let embedding = embedding.into_iter().next().unwrap();
            let confidence = self.calculate_confidence(&text, query);
            
            hypothetical_documents.push(HypotheticalDocument {
                id,
                text,
                embedding: Some(embedding),
                confidence,
            });
        }

        // Generate combined embedding
        let combined_embedding = if self.config.combine_with_query {
            Some(self.create_combined_embedding(query, &hypothetical_documents).await?)
        } else {
            None
        };

        // Calculate expansion quality
        let expansion_quality = self.calculate_expansion_quality(&hypothetical_documents);

        Ok(HydeExpansion {
            original_query: query.to_string(),
            hypothetical_documents,
            combined_embedding,
            expansion_quality,
        })
    }

    /// Generate hypothetical documents for the given query
    async fn generate_hypothetical_documents(&self, query: &str) -> Result<Vec<String>> {
        let prompt = self.build_hyde_prompt(query);
        self.llm_service.generate_text(&prompt, &self.config).await
    }

    /// Build the prompt for generating hypothetical documents
    fn build_hyde_prompt(&self, query: &str) -> String {
        format!(
            r#"Given the following query, write {} high-quality, detailed document passages that would contain the answer to this query. Each passage should be informative, well-structured, and directly relevant to the query.

Query: {query}

Generate {num_docs} hypothetical document passages:

1."#,
            self.config.num_documents,
            query = query,
            num_docs = self.config.num_documents
        )
    }

    /// Calculate confidence score for a hypothetical document
    fn calculate_confidence(&self, document: &str, query: &str) -> f32 {
        // Simple confidence calculation based on text overlap and quality
        let query_lower = query.to_lowercase();
        let query_words: std::collections::HashSet<&str> = query_lower
            .split_whitespace()
            .collect();
        
        let doc_lower = document.to_lowercase();
        let doc_words: std::collections::HashSet<&str> = doc_lower
            .split_whitespace()
            .collect();

        let overlap = query_words.intersection(&doc_words).count();
        let total_query_words = query_words.len();
        
        if total_query_words == 0 {
            return 0.0;
        }

        let overlap_score = overlap as f32 / total_query_words as f32;
        
        // Factor in document length (longer documents tend to be more detailed)
        let length_score = (document.len() as f32 / 500.0).min(1.0);
        
        // Combine scores
        (overlap_score * 0.6 + length_score * 0.4).min(1.0)
    }

    /// Create a combined embedding from query and hypothetical documents
    async fn create_combined_embedding(
        &self,
        query: &str,
        hypothetical_documents: &[HypotheticalDocument],
    ) -> Result<EmbeddingVector> {
        // Get query embedding
        let query_embedding = self.embedding_service.embed(&[query.to_string()]).await?;
        let query_embedding = query_embedding.into_iter().next().unwrap();
        
        // Collect all embeddings with weights
        let mut weighted_embeddings = Vec::new();
        
        // Add query embedding with weight
        weighted_embeddings.push((query_embedding, 1.0));
        
        // Add hypothetical document embeddings with confidence weights
        for doc in hypothetical_documents {
            if let Some(ref embedding) = doc.embedding {
                weighted_embeddings.push((embedding.clone(), doc.confidence));
            }
        }

        // Calculate weighted average
        self.calculate_weighted_average(&weighted_embeddings)
    }

    /// Calculate weighted average of embeddings
    fn calculate_weighted_average(&self, embeddings: &[(EmbeddingVector, f32)]) -> Result<EmbeddingVector> {
        if embeddings.is_empty() {
            return Err(LetheError::validation("embeddings", "No embeddings to average"));
        }

        let dimension = embeddings[0].0.data.len();
        let mut result = vec![0.0; dimension];
        let mut total_weight = 0.0;

        for (embedding, weight) in embeddings {
            if embedding.data.len() != dimension {
                return Err(LetheError::validation("dimension", "Embedding dimension mismatch"));
            }

            for (i, &value) in embedding.data.iter().enumerate() {
                result[i] += value * weight;
            }
            total_weight += weight;
        }

        // Normalize by total weight
        if total_weight > 0.0 {
            for value in &mut result {
                *value /= total_weight;
            }
        }

        Ok(EmbeddingVector {
            data: result,
            dimension,
        })
    }

    /// Calculate the overall quality of the expansion
    fn calculate_expansion_quality(&self, hypothetical_documents: &[HypotheticalDocument]) -> f32 {
        if hypothetical_documents.is_empty() {
            return 0.0;
        }

        // Average confidence of hypothetical documents
        let avg_confidence: f32 = hypothetical_documents
            .iter()
            .map(|doc| doc.confidence)
            .sum::<f32>() / hypothetical_documents.len() as f32;

        // Factor in diversity (simple measure: average text length variance)
        let lengths: Vec<f32> = hypothetical_documents
            .iter()
            .map(|doc| doc.text.len() as f32)
            .collect();
        
        let avg_length = lengths.iter().sum::<f32>() / lengths.len() as f32;
        let variance = lengths
            .iter()
            .map(|&len| (len - avg_length).powi(2))
            .sum::<f32>() / lengths.len() as f32;
        
        let diversity_score = (variance / avg_length).min(1.0);

        // Combine metrics
        avg_confidence * 0.8 + diversity_score * 0.2
    }

    /// Get the best hypothetical documents based on confidence
    pub fn get_best_documents<'a>(&self, expansion: &'a HydeExpansion, limit: usize) -> Vec<&'a HypotheticalDocument> {
        let mut documents = expansion.hypothetical_documents.iter().collect::<Vec<_>>();
        documents.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));
        documents.into_iter().take(limit).collect()
    }
}

/// Mock LLM service for testing
#[cfg(test)]
pub struct MockLlmService {
    responses: std::collections::HashMap<String, Vec<String>>,
}

#[cfg(test)]
impl MockLlmService {
    pub fn new() -> Self {
        Self {
            responses: std::collections::HashMap::new(),
        }
    }

    pub fn add_response(&mut self, prompt: String, responses: Vec<String>) {
        self.responses.insert(prompt, responses);
    }
}

#[cfg(test)]
#[async_trait]
impl LlmService for MockLlmService {
    async fn generate_text(&self, prompt: &str, _config: &HydeConfig) -> Result<Vec<String>> {
        // For testing, generate simple responses based on the query
        if prompt.contains("machine learning") {
            Ok(vec![
                "Machine learning is a subset of artificial intelligence that enables computers to learn and make decisions from data without explicit programming.".to_string(),
                "Modern machine learning algorithms include deep learning neural networks, random forests, and support vector machines.".to_string(),
                "Applications of machine learning span computer vision, natural language processing, and predictive analytics.".to_string(),
            ])
        } else {
            Ok(vec![
                "This is a hypothetical document about the query topic.".to_string(),
                "Another relevant document with detailed information.".to_string(),
                "A third document providing additional context.".to_string(),
            ])
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::embeddings::FallbackEmbeddingService;

    #[tokio::test]
    async fn test_hyde_expansion() {
        let llm_service = Arc::new(MockLlmService::new());
        let embedding_service = Arc::new(FallbackEmbeddingService::new(384));
        let config = HydeConfig::default();
        
        let hyde_service = HydeService::new(llm_service, embedding_service, config);
        
        let expansion = hyde_service.expand_query("What is machine learning?").await.unwrap();
        
        assert_eq!(expansion.original_query, "What is machine learning?");
        assert_eq!(expansion.hypothetical_documents.len(), 3);
        assert!(expansion.expansion_quality > 0.0);
        
        for doc in &expansion.hypothetical_documents {
            assert!(!doc.text.is_empty());
            assert!(doc.confidence >= 0.0 && doc.confidence <= 1.0);
            assert!(doc.embedding.is_some());
        }
    }

    #[test]
    fn test_confidence_calculation() {
        let llm_service = Arc::new(MockLlmService::new());
        let embedding_service = Arc::new(FallbackEmbeddingService::new(384));
        let config = HydeConfig::default();
        
        let hyde_service = HydeService::new(llm_service, embedding_service, config);
        
        let query = "machine learning algorithms";
        let document = "Machine learning algorithms are used to build predictive models and analyze data patterns.";
        
        let confidence = hyde_service.calculate_confidence(document, query);
        assert!(confidence > 0.0 && confidence <= 1.0);
    }

    #[test]
    fn test_weighted_average_embeddings() {
        let llm_service = Arc::new(MockLlmService::new());
        let embedding_service = Arc::new(FallbackEmbeddingService::new(384));
        let config = HydeConfig::default();
        
        let hyde_service = HydeService::new(llm_service, embedding_service, config);
        
        let embeddings = vec![
            (EmbeddingVector { data: vec![1.0, 0.0, 0.0], dimension: 3 }, 1.0),
            (EmbeddingVector { data: vec![0.0, 1.0, 0.0], dimension: 3 }, 1.0),
        ];
        
        let result = hyde_service.calculate_weighted_average(&embeddings).unwrap();
        assert_eq!(result.data, vec![0.5, 0.5, 0.0]);
        assert_eq!(result.dimension, 3);
    }

    #[test]
    fn test_best_documents_selection() {
        let expansion = HydeExpansion {
            original_query: "test".to_string(),
            hypothetical_documents: vec![
                HypotheticalDocument {
                    id: "1".to_string(),
                    text: "doc1".to_string(),
                    embedding: None,
                    confidence: 0.9,
                },
                HypotheticalDocument {
                    id: "2".to_string(),
                    text: "doc2".to_string(),
                    embedding: None,
                    confidence: 0.7,
                },
                HypotheticalDocument {
                    id: "3".to_string(),
                    text: "doc3".to_string(),
                    embedding: None,
                    confidence: 0.8,
                },
            ],
            combined_embedding: None,
            expansion_quality: 0.8,
        };

        let llm_service = Arc::new(MockLlmService::new());
        let embedding_service = Arc::new(FallbackEmbeddingService::new(384));
        let config = HydeConfig::default();
        
        let hyde_service = HydeService::new(llm_service, embedding_service, config);
        
        let best = hyde_service.get_best_documents(&expansion, 2);
        assert_eq!(best.len(), 2);
        assert_eq!(best[0].confidence, 0.9);
        assert_eq!(best[1].confidence, 0.8);
    }
}